server:
  port: 8090

spring:
  application:
    name: "cards"
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071"
  datasource:
    url: jdbc:mysql://localhost:3307/cardsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql: # Carica in automatico il file ./schema.sql
    init:
      mode: always
  logging:
    level:
      root: INFO
      org.springframework.web: DEBUG
      com.example.accounts: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"