server:
  port: 8071

spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
         git:
           uri: https://github.com/Ruma303/spring-microservices-eazybytes-config.git
           default-label: main
           timeout: 5
           clone-on-start: true
           force-pull: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


# Inserito nelle variabili d'ambiente del modulo configserver
#encrypt:
#  key: ""

management:
  endpoints:
    web:
      exposure:
        exclude: encrypt, decrypt