server:
  port: 8071

spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
         native:
            search-location: "file:///Users//ruma//Library//Mobile Documents//com~apple~CloudDocs//Sites//Coding//Spring Boot//Lessons//spring-microservices//config"
