server:
  port: 8072

spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lowerCaseServiceId: true
          httpclient:
            connect-timeout: 1000           # 1 secondo per stabilire connessione
            response-timeout: 2s            # 2 secondi per ricevere risposta
#      # Esempio di disabilitazione timeout di risposta globale per singole rotte
#      routes:
#        - id: per_route_timeouts
#          uri: http://localhost:8072/eazybank/loans/api/contact-info
#          predicates:
#            - Path=/delay/{timeout}
#          metadata:
#            connect-timeout: 2000       # in ms
#            response-timeout: 200      # in ms

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
      health:
        probes:
          enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8070/eureka/}

info:
  app:
    name: "gatewayserver"
    description: "Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com.springmicroservices.accounts: DEBUG

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000

resilience4j.retry:
  configs:
    default:
      maxRetryAttempts: 3
      waitDuration: 500
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2