server:
  port: 8100

spring:
  application:
    name: "loans"
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071"
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: 'sa'
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql: # Carica in automatico il file ./schema.sql
    init:
      mode: always
  logging:
    level:
      root: INFO
      org.springframework.web: DEBUG
      com.example.loans: DEBUG
      com.netflix.discovery: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
        exclude: encrypt, decrypt
  endpoint:
    shutdown:
      access: unrestricted
      health:
        probes:
          enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  instance:
    prefer-ip-address: true
  client:
    leaseRenewalIntervalInSeconds: 30  # default 30
    leaseExpirationDurationInSeconds: 90 # default 90
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8070/eureka/}

info:
  app:
    name: "loans"
    description: "Eazy Bank Loans Application"
    version: "1.0.0"

logging:
  level:
    com.springmicroservices.loans: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000