services:

  redis:
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      timeout: 10s
      retries: 10
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "rumadev/configserver:s10"
    container_name: configserver-ms
    platform: linux/amd64
    ports:
      - "8071:8071"
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -q http://localhost:8071/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "rumadev/eurekaserver:s10"
    container_name: eurekaserver-ms
    platform: linux/amd64
    ports:
      - "8070:8070"
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -q http://localhost:8070/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "rumadev/accounts:s10"
    container_name: accounts-ms
    platform: linux/amd64
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -q http://localhost:8080/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "rumadev/cards:s10"
    container_name: cards-ms
    platform: linux/amd64
    ports:
      - "8090:8090"
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -q http://localhost:8090/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "rumadev/loans:s10"
    container_name: loans-ms
    platform: linux/amd64
    ports:
      - "8100:8100"
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -q http://localhost:8100/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  gatewayserver:
    image: "rumadev/gatewayserver:s10"
    container_name: gatewayserver-ms
    platform: linux/amd64
    ports:
      - "8072:8072"
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
      accounts:
        condition: service_healthy
      cards:
        condition: service_healthy
      loans:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
      SPRING_DATA_REDIS_CONNECTION_TIMEOUT: 2s
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_TIMEOUT: 1s
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -q http://localhost:8072/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  rumadev:
    driver: bridge