server:
  port: 8071

spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
         git:
           uri: ${GIT_CONFIG_REPO_URI}
           username: ${GIT_CONFIG_REPO_USERNAME}
           password: ${GIT_CONFIG_REPO_TOKEN}
           default-label: main
           timeout: 5
           clone-on-start: true
           force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
      health:
        probes:
          enabled: true
  metrics:
    export:
      prometheus:
        enabled: true